apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: redis-cluster-dev-node00
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    name: redis-cluster-dev-node00
    sname: redis-cluster
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: redis-cluster-dev-node00
        sname: redis-cluster
    spec:
      nodeSelector:
        redis: ZONENUMBER
      volumes:
        - name: volume-deployer
          configMap:
            name: deployer
            defaultMode: 440
      containers:
      - image: manoframa9/jkpipeline-rediscluster:GITTAG
        imagePullPolicy: Always
        name: redis-cluster-dev-node00
        ports:
        - containerPort: 6379
          protocol: TCP
        - containerPort: 16379
          protocol: TCP
        resources: {}
        volumeMounts:
            - name: volume-deployer
              mountPath: /confmap
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: msartifactory
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
