apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis-cluster-dev-node00
spec:
  clusterIP: None
  ports:
  - name: redis-dev-00
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: redis-dev-00-cluster
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    name: redis-cluster-dev-node00
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
